version: '3.8'

services:
  neo4j:
    image: neo4j:5.16.0-community
    container_name: neo4j-tgr
    ports:
      - "7474:7474" # Browser
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
    restart: unless-stopped
